version: 2.1

jobs:
  mvn_package:
    parameters:
      project:
        type: string

    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/instrumenting-java-for-prometheus/<< parameters.project >>

    steps:
    - checkout:
        path: ~/instrumenting-java-for-prometheus/
    - run:
        command: mvn -B clean package
    - setup_remote_docker
    - run: docker build -t << parameters.project >>:latest .
    - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD quay.io
    - run: docker tag << parameters.project >>:latest "quay.io/simonpasquier/<< parameters.project >>:latest"
    - run: docker push quay.io/simonpasquier/<< parameters.project >>

  micrometer:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/instrumenting-java-for-prometheus/micrometer
    steps:
    - checkout:
        path: ~/instrumenting-java-for-prometheus/
    - run: gradle -q clean assemble
    - setup_remote_docker
    - run: docker build -t micrometer:latest .
    - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD quay.io
    - run: docker tag micrometer:latest "quay.io/simonpasquier/micrometer:latest"
    - run: docker push quay.io/simonpasquier/micrometer

workflows:
  version: 2
  master:
    jobs:
    - mvn_package:
        context: Quay
        name: client_java
        project: client_java
    - mvn_package:
        context: Quay
        name: mp_metrics
        project: mp_metrics
    - micrometer:
        context: Quay
        name: mp_metrics
