# my global config
global:
  scrape_interval:     10s
  evaluation_interval: 15s

# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'kafka'
    static_configs:
      - targets:
        - jmx_exporter_kafka_1:9098

  - job_name: 'web'
    static_configs:
      - targets:
        - client_java:8080
        - mp_metrics:8080
